BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Items" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "Items" VALUES (1,'Healing Potion');
INSERT INTO "Items" VALUES (2,'OO Pillar 2');
COMMIT;
